version: 2

models:
  - name: aux_operadora_jae_cliente_historico
    columns:
      - name: nome
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: documento
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: id_cliente
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
  - name: aux_operadora_jae_historico
    columns:
      - name: id_cliente
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
  - name: aux_operadora_cliente_join_jae_historico
    columns:
      - name: operadora
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: documento
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: id_cliente
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
  - name: aux_operadora_jae_stu_historico
    columns:
      - name: operadora_jae
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: operadora_stu
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: documento
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: id_cliente
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'