{{
    config(
        materialized="view",
    )
}}


with
    dados_manuais as (
        select *
        from
            unnest(
                [
                    struct(  -- Processo 000399006676/2026-28
                        '2026-04-02' as data_inicio,
                        '2026-04-02' as data_fim,
                        '2026-04-02T18:00:00' as faixa_horaria_inicio,
                        '2026-04-02T23:59:59' as faixa_horaria_fim,
                        cast([] as array<string>) as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n° 000300.023357/2026-29.
                        '2026-06-01' as data_inicio,
                        '2026-06-15' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "160",
                            "161",
                            "162",
                            "167",
                            "169",
                            "232",
                            "319",
                            "361",
                            "SV319",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "805",
                            "SP805",
                            "LECD127",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134",
                            "LECD136",
                            "LECD138"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo nº 000300.021698/2026-60.
                        '2026-05-18' as data_inicio,
                        '2026-05-31' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "160",
                            "161",
                            "162",
                            "167",
                            "169",
                            "232",
                            "319",
                            "361",
                            "SV319",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "805",
                            "SP805",
                            "LECD127",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134",
                            "LECD136",
                            "LECD137",
                            "LECD138"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo nº 000300.021698/2026-60.
                        '2026-05-16' as data_inicio,
                        '2026-05-17' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "161",
                            "167",
                            "169",
                            "232",
                            "361",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "805",
                            "SP805",
                            "LECD127",
                            "LECD128",
                            "LECD129",
                            "LECD130",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134",
                            "LECD136",
                            "LECD138"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n°  000300.019252/2026-75.
                        '2026-05-01' as data_inicio,
                        '2026-05-15' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "161",
                            "167",
                            "169",
                            "232",
                            "361",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "805",
                            "SP805",
                            "LECD127",
                            "LECD128",
                            "LECD129",
                            "LECD130",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134",
                            "LECD135",
                            "LECD136",
                            "LECD138"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n° 000300.014987/2026-11 e Processo n° 000300.017825/2026-26
                        '2026-04-01' as data_inicio,
                        '2026-04-30' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "161",
                            "167",
                            "169",
                            "232",
                            "361",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "805",
                            "SP805",
                            "LECD127",
                            "LECD128",
                            "LECD129",
                            "LECD130",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134",
                            "LECD136",
                            "LECD137",
                            "LECD138"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n° 000300.013241/2026-81
                        '2026-03-16' as data_inicio,
                        '2026-03-31' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "161",
                            "167",
                            "169",
                            "232",
                            "361",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "805",
                            "SP805",
                            "LECD127",
                            "LECD128",
                            "LECD129",
                            "LECD130",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134",
                            "LECD136",
                            "LECD137",
                            "LECD138"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo: 000399.002687/2026-39
                        '2026-03-05' as data_inicio,
                        '2026-03-05' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        ["321", "324", "325", "326", "329", "616"] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n° 000300.005989/2026-19 e Processo SEI: 000300.009756/2026-87
                        '2026-02-16' as data_inicio,
                        '2026-03-15' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "161",
                            "167",
                            "169",
                            "232",
                            "361",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "805",
                            "SP805",
                            "LECD127",
                            "LECD128",
                            "LECD129",
                            "LECD130",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134",
                            "LECD136",
                            "LECD137",
                            "LECD138"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n° 000300.005989/2026-19
                        '2026-01-16' as data_inicio,
                        '2026-02-15' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "161",
                            "167",
                            "169",
                            "232",
                            "361",
                            "409",
                            "410",
                            "416",
                            "435",
                            "461",
                            "473",
                            "552",
                            "583",
                            "584",
                            "SP805",
                            "LECD127",
                            "LECD128",
                            "LECD129",
                            "LECD130",
                            "LECD131",
                            "LECD132",
                            "LECD133",
                            "LECD134"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n° 000300.005989/2026-19
                        '2026-02-01' as data_inicio,
                        '2026-02-15' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        ["805", "LECD136", "LECD137"] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo n° 000300.001720/2026-55
                        '2026-01-01' as data_inicio,
                        '2026-01-15' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "104",
                            "107",
                            "109",
                            "161",
                            "167",
                            "169",
                            "409",
                            "410",
                            "435",
                            "473",
                            "583",
                            "584",
                            "LECD127",
                            "LECD128",
                            "552",
                            "SP805",
                            "361",
                            "LECD129",
                            "232"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo nº 000300.000641/2026-27
                        '2025-12-22' as data_inicio,
                        '2025-12-26' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "232",
                            "552",
                            "SP805",
                            "361",
                            "104",
                            "107",
                            "161",
                            "169",
                            "409",
                            "410",
                            "435",
                            "473",
                            "583",
                            "584",
                            "109"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo nº 000300.000641/2026-27
                        '2025-12-29' as data_inicio,
                        '2025-12-31' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        [
                            "232",
                            "552",
                            "SP805",
                            "361",
                            "104",
                            "107",
                            "161",
                            "169",
                            "409",
                            "410",
                            "435",
                            "473",
                            "583",
                            "584",
                            "109",
                            "167",
                            "LECD127",
                            "LECD128",
                            "LECD129"
                        ] as servicos,
                        true as indicador_viagem_dentro_limite
                    ),
                    struct(  -- Processo.rio MTR-OFI-2025/06240
                        '2025-09-16' as data_inicio,
                        '2025-09-16' as data_fim,
                        cast(null as string) as faixa_horaria_inicio,
                        cast(null as string) as faixa_horaria_fim,
                        ["161", "LECD110", "583", "584", "109"] as servicos,
                        true as indicador_viagem_dentro_limite
                    )
                ]
            )
        with
        offset as priority
    )
select
    date(data_inicio) as data_inicio,
    date(data_fim) as data_fim,
    datetime(faixa_horaria_inicio) as faixa_horaria_inicio,
    datetime(faixa_horaria_fim) as faixa_horaria_fim,
    servico,
    indicador_viagem_dentro_limite,
    priority
from dados_manuais
left join unnest(servicos) as servico
