[project]
name = "rj_segovi__dump_db_1746"
version = "0.1.0"
description = "Pipeline dump_db_1746 da secretaria rj_segovi"

[tool.uv.sources]
iplanrio = { git = "https://github.com/prefeitura-rio/iplanrio.git" , rev = "a2001c8445ad0f17019bf9d179f38ffaa3603d2f"}
