automations:
  - name: Crash Zombie Flows
    description: Crash flows without heartbeats
    enabled: true
    trigger:
      type: event
      posture: Proactive
      after:
        - prefect.flow-run.heartbeat
      expect:
        - prefect.flow-run.heartbeat
        - prefect.flow-run.Completed
        - prefect.flow-run.Failed
        - prefect.flow-run.Cancelled
        - prefect.flow-run.Crashed
      threshold: 1
      within: 300 # 5 minutes
      for_each:
        - prefect.resource.id
    actions:
      - type: change-flow-run-state
        state: CRASHED
        message: "Flow run has not sent a heartbeat in over 5 minutes, marking as
          CRASHED."
