name: Build and push root image

on:
  push:
    branches:
      - master
      - devops/*
    paths:
      - Dockerfile
      - .github/workflows/build-and-push-root-image.yaml
  workflow_dispatch:
env:
  github_repository: rj-smtr/pipelines_v3
jobs:
  build-and-push-root-image:
    name: Build and push root image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push root image
        uses: ./.github/actions/build-and-push-root-image
        with:
          repository: ${{ env.github_repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-prefect-flows-staging:
    name: Deploy Prefect staging flows
    needs: build-and-push-root-image
    runs-on: k8s
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy Prefect flows
        uses: ./.github/actions/deploy-prefect-flows
        with:
          environment: staging
          force_deploy: "1"
          pipelines_path: ./pipelines
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          # ts_tags: tag:prefect-cicd
          # ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          # ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: ${{ vars.LOG_LEVEL }}

  deploy-prefect-flows-prod:
    name: Deploy Prefect prod flows
    needs: build-and-push-root-image
    runs-on: k8s
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy Prefect flows
        uses: ./.github/actions/deploy-prefect-flows
        with:
          environment: prod
          force_deploy: "1"
          pipelines_path: ./pipelines
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          # ts_tags: tag:prefect-cicd
          # ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          # ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: ${{ vars.LOG_LEVEL }}
