name: Build and push runner image

on:
  push:
    branches: 
      - main
      - devops/*
    paths:
      - 'runner.Dockerfile'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: build-runner-image
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./runner.Dockerfile
          push: true
          tags: |
            ghcr.io/rj-smtr/pipelines_v3/runner:latest
            ghcr.io/rj-smtr/pipelines_v3/runner:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max