name: Automations CD
on:
  push:
    branches:
      - staging/*
      - devops/*
    paths:
      - automations/**
      - .github/workflows/cd_automations.yaml

env:
  PREFECT_API_URL: ${{ secrets.PREFECT_WEB_API_URL }}
  PREFECT_CLIENT_CUSTOM_HEADERS: ${{ secrets.AUTH_HEADERS }}

jobs:
  create-automations:
    name: Create automations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install project dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev unixodbc-dev gcc build-essential
          uv sync --all-packages

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Create automations
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          echo "${{ steps.changed-files.outputs.changed_files }}"
          for file in $(echo "${{ steps.changed-files.outputs.changed_files }}" | tr ',' '\n'); do
            echo "Processing $file"
            uv run prefect automation create --file $file
          done
