name: CD - DBT Docs Generation and Upload

on:
  push:
    branches:
      - master
      - staging/*
    # paths:
    #   - 'queries/**'
    #   - '.github/workflows/cd_dbt_docs.yaml'
  workflow_dispatch:

jobs:
  generate-and-upload-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev unixodbc-dev gcc build-essential
          uv sync --all-packages

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          version: "latest"

      - name: Setup credentials for dbt
        run: |-
          
          echo "Mounting files from env..."

          echo "${{ secrets.GKE_SA_KEY }}" > /tmp/credentials.json

      - name: Generate dbt docs
        run: |
          cd queries
          uv run dbt deps --target prod
          uv run dbt docs generate --static --target prod

      - name: Upload docs to GCS
        run: |
          gsutil -m cp queries/target/index.html gs://${{ secrets.GCS_BUCKET_NAME }}/dbt-docs/
          gsutil -m cp queries/target/manifest.json gs://${{ secrets.GCS_BUCKET_NAME }}/dbt-docs/
      # - name: Notify on success
      #   if: success()
      #   run: echo "DBT docs generated and uploaded successfully to GCS"

      # - name: Notify on failure
      #   if: failure()
      #   run: echo "DBT docs generation or upload failed"
