name: Deploy Prefect flows

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      force_deploy:
        type: string
        default: 0
      prefect_api_url:
        required: true
        type: string
      pipelines_path:
        required: true
        type: string
      ts_tags:
        required: true
        type: string

jobs:
  deploy-prefect-flows:
    name: Deploy Prefect flows
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: ${{ inputs.ts_tags }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Deploy Prefect flows
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          PREFECT_API_URL: ${{ inputs.prefect_api_url }}
          PIPELINES_PATH: ${{ inputs.pipelines_path }}
          FORCE_DEPLOY: ${{ inputs.force_deploy }}
          GITHUB_SHA: ${{ github.sha }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
        run: uv run .github/scripts/deploy_prefect_flows.py
