name: Deploy Prefect flows (prod)

on:
  push:
    branches:
      - master
    paths:
      - pipelines/**
  workflow_dispatch:

jobs:
  deploy-prefect-prod-flows:
    name: Deploy Prefect prod flows
    secrets: inherit
    uses: ./.github/workflows/deploy-prefect-flows.yaml
    with:
      environment: prod
      pipelines_path: ./pipelines
      prefect_api_url: https://prefect.squirrel-regulus.ts.net/api
      ts_tags: tag:prefect-cicd
