name: Deploy Prefect flows

on:
  push:
    branches:
      - main
    paths:
      - pipelines/*

jobs:
  deploy:
    name: Deploy Prefect flows
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Prefect
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          for d in pipelines/*; do
            if [ -f "$d/prefect.yaml" ]; then
              (cd "$d" && uv run --with "prefect>=3.4.3" -- prefect deploy -n "$(basename "$d")")
            fi
          done
