name: Deploy Prefect flows (staging)

on:
  push:
    branches:
      - staging/*
    paths:
      - pipelines/**
  workflow_dispatch:

jobs:
  deploy-prefect-staging-flows:
    name: Deploy Prefect staging flows
    secrets: inherit
    uses: ./.github/workflows/deploy-prefect-flows.yaml
    with:
      environment: staging
      pipelines_path: ./pipelines
      prefect_api_url: https://prefect.squirrel-regulus.ts.net/api
      ts_tags: tag:prefect-cicd
