name: Actions Runner Controller Demo
on:
  push:
    branches:
      - test/*

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: k8s
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
